### ISSUE TITLE
Line breaks seem to cause this plugin to break

### ISSUE THREAD

**Issue by bytenik** [ekwoka/vite-plugin-using#2]
The following code works using this plugin:

```
const comparator = (x: Point) => x.x - point[timestampColumnName];
using searchRes = binarySearch(this.highchartSeries!.points, comparator);
```

The following code does not work:
```
using searchRes = binarySearch(
    this.highchartSeries!.points,
    (x: Point) => x.x - point[timestampColumnName],
);
```

It generates the following error:
```
11:10:36 PM [vite] Internal server error: 
  × Expression expected
     ╭─[file.ts:323:1]
 323 │                         
 324 │       const searchRes = binarySearch(
 325 │                             
 326 │       try {
     ·       ───
 327 │         this.highchartSeries!.points,
 328 │                             (x: Point) => x.x - point[timestampColumnName],
 329 │                         );
     ╰────


Caused by:
    Syntax Error
  Plugin: vite:react-swc
  File: file.ts:323:1
  

[TypeScript] Found 0 errors. Watching for file changes.
```

From the error, it seems like the transpiled `try` block is starting on the wrong line.

**Comment by bytenik** [comment]
Having now read the source, I'm not sure that you can actually transpile this using a regex.

**Comment by ekwoka** [comment]
This is just a simple thing made for fun. Could be made more advanced.

For a case like above I'd just recommend making the thing in another variable before using. And just use that.

But I'll check it out

**Comment by ekwoka** [comment]
Closing as package is deprecated, since it's supported by Vite through esbuild.
