### ISSUE TITLE
Deprecate in favor of `esbuild.target: 'es2022'`

### ISSUE THREAD

**Issue by soulofmischief** [ekwoka/vite-plugin-using#4]
As mentioned in https://github.com/vitejs/vite/discussions/14327#discussioncomment-7275394

```js
{
  esbuild: {
    target: 'es2022'
  }
}
```

properly transforms `using` statements using an AST, which prevents bugs such as https://github.com/ekwoka/vite-plugin-using/issues/2.

It would be best to mark this project as deprecated, with a note about the correct configuration.

**Comment by ekwoka** [comment]
Nice!

this was mostly a fun play thing, but that's even better
